using System.Text;

namespace EFCore.StronglyTyped;

internal static class Emitter
{
    // ── Attribute source emitted into every consuming compilation ────────────

    internal const string AttributeSource = """
        // <auto-generated/>
        #nullable enable

        namespace EFCore.StronglyTyped
        {
            using System;

            /// <summary>Marks a <c>readonly partial struct</c> as a strongly-typed ID.
            /// The source generator will emit equality, comparison, explicit conversion operators,
            /// an EF Core <c>ValueConverter</c> nested class, and a System.Text.Json
            /// <c>JsonConverter</c> nested class.</summary>
            [AttributeUsage(AttributeTargets.Struct)]
            public sealed class StronglyTypedIdAttribute : Attribute
            {
                /// <summary>The primitive type that backs the ID value.</summary>
                public BackingType BackingType { get; }

                /// <summary>Initialises a new <see cref="StronglyTypedIdAttribute"/>.</summary>
                /// <param name="backingType">The primitive type used to store the ID. Defaults to <see cref="BackingType.Guid"/>.</param>
                public StronglyTypedIdAttribute(BackingType backingType = BackingType.Guid)
                {
                    BackingType = backingType;
                }
            }

            /// <summary>Specifies the underlying primitive type for a strongly-typed ID.</summary>
            public enum BackingType
            {
                /// <summary>Backed by <see cref="System.Guid"/>.</summary>
                Guid = 0,
                /// <summary>Backed by <see cref="int"/>.</summary>
                Int = 1,
                /// <summary>Backed by <see cref="long"/>.</summary>
                Long = 2,
                /// <summary>Backed by <see cref="string"/>.</summary>
                String = 3,
            }
        }
        """;

    // ── Per-type source generation ────────────────────────────────────────────

    internal static string Emit(TypeModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (model.Namespace is not null)
        {
            sb.AppendLine($"namespace {model.Namespace}");
            sb.AppendLine("{");
        }

        var (backingTypeName, jsonReadExpr, jsonWriteMethod, hasNew, hasEmpty) = GetBackingTypeInfo(model.BackingType);

        sb.AppendLine($"    [System.Text.Json.Serialization.JsonConverter(typeof({model.TypeName}.SystemTextJsonConverter))]");
        sb.AppendLine($"    public readonly partial struct {model.TypeName} :");
        sb.AppendLine($"        System.IEquatable<{model.TypeName}>,");
        sb.AppendLine($"        System.IComparable<{model.TypeName}>");
        sb.AppendLine("    {");

        // Value property
        sb.AppendLine($"        /// <summary>The underlying <see cref=\"{backingTypeName}\"/> value.</summary>");
        sb.AppendLine($"        public {backingTypeName} Value {{ get; }}");
        sb.AppendLine();

        // Constructor
        sb.AppendLine($"        /// <summary>Initialises a new <see cref=\"{model.TypeName}\"/> with the specified value.</summary>");
        sb.AppendLine($"        public {model.TypeName}({backingTypeName} value) => Value = value;");
        sb.AppendLine();

        // Static factory / empty (Guid only)
        if (hasNew)
        {
            sb.AppendLine($"        /// <summary>Creates a new <see cref=\"{model.TypeName}\"/> with a random <see cref=\"System.Guid\"/>.</summary>");
            sb.AppendLine($"        public static {model.TypeName} New() => new(System.Guid.NewGuid());");
            sb.AppendLine();
        }

        if (hasEmpty)
        {
            sb.AppendLine($"        /// <summary>Gets a <see cref=\"{model.TypeName}\"/> whose value is <see cref=\"System.Guid.Empty\"/>.</summary>");
            sb.AppendLine($"        public static {model.TypeName} Empty => new(System.Guid.Empty);");
            sb.AppendLine();
        }

        // Equality
        sb.AppendLine($"        /// <inheritdoc/>");
        sb.AppendLine($"        public bool Equals({model.TypeName} other) => Value == other.Value;");
        sb.AppendLine();
        sb.AppendLine($"        /// <inheritdoc/>");
        sb.AppendLine($"        public override bool Equals(object? obj) => obj is {model.TypeName} other && Equals(other);");
        sb.AppendLine();
        sb.AppendLine($"        /// <inheritdoc/>");
        sb.AppendLine($"        public override int GetHashCode() => Value.GetHashCode();");
        sb.AppendLine();

        // ToString
        sb.AppendLine($"        /// <inheritdoc/>");
        sb.AppendLine($"        public override string ToString() => Value.ToString(){(model.BackingType == BackingTypeKind.String ? " ?? string.Empty" : "")};");
        sb.AppendLine();

        // CompareTo
        sb.AppendLine($"        /// <inheritdoc/>");

        if (model.BackingType == BackingTypeKind.String)
            sb.AppendLine($"        public int CompareTo({model.TypeName} other) => System.StringComparer.Ordinal.Compare(Value, other.Value);");
        else
            sb.AppendLine($"        public int CompareTo({model.TypeName} other) => Value.CompareTo(other.Value);");

        sb.AppendLine();

        // Operators
        sb.AppendLine($"        /// <summary>Equality operator.</summary>");
        sb.AppendLine($"        public static bool operator ==({model.TypeName} left, {model.TypeName} right) => left.Equals(right);");
        sb.AppendLine();
        sb.AppendLine($"        /// <summary>Inequality operator.</summary>");
        sb.AppendLine($"        public static bool operator !=({model.TypeName} left, {model.TypeName} right) => !left.Equals(right);");
        sb.AppendLine();

        // Comparison operators
        sb.AppendLine($"        /// <summary>Less-than operator.</summary>");
        sb.AppendLine($"        public static bool operator <({model.TypeName} left, {model.TypeName} right) => left.CompareTo(right) < 0;");
        sb.AppendLine();
        sb.AppendLine($"        /// <summary>Greater-than operator.</summary>");
        sb.AppendLine($"        public static bool operator >({model.TypeName} left, {model.TypeName} right) => left.CompareTo(right) > 0;");
        sb.AppendLine();
        sb.AppendLine($"        /// <summary>Less-than-or-equal operator.</summary>");
        sb.AppendLine($"        public static bool operator <=({model.TypeName} left, {model.TypeName} right) => left.CompareTo(right) <= 0;");
        sb.AppendLine();
        sb.AppendLine($"        /// <summary>Greater-than-or-equal operator.</summary>");
        sb.AppendLine($"        public static bool operator >=({model.TypeName} left, {model.TypeName} right) => left.CompareTo(right) >= 0;");
        sb.AppendLine();

        // Explicit conversions
        sb.AppendLine($"        /// <summary>Converts a <see cref=\"{model.TypeName}\"/> to its underlying <see cref=\"{backingTypeName}\"/>.</summary>");
        sb.AppendLine($"        public static explicit operator {backingTypeName}({model.TypeName} id) => id.Value;");
        sb.AppendLine();
        sb.AppendLine($"        /// <summary>Converts a <see cref=\"{backingTypeName}\"/> to a <see cref=\"{model.TypeName}\"/>.</summary>");
        sb.AppendLine($"        public static explicit operator {model.TypeName}({backingTypeName} value) => new(value);");
        sb.AppendLine();

        // EF Core ValueConverter nested class
        sb.AppendLine($"        /// <summary>EF Core <c>ValueConverter</c> for <see cref=\"{model.TypeName}\"/>.</summary>");
        sb.AppendLine($"        /// <remarks>Register via <c>modelBuilder.Entity&lt;T&gt;().Property(x => x.Id).HasConversion(new {model.TypeName}.EfCoreValueConverter())</c>");
        sb.AppendLine($"        /// or call <c>modelBuilder.ApplyStronglyTypedIdConversions()</c> if using the EFCore.StronglyTyped.EFCore extension package.</remarks>");
        sb.AppendLine($"        public sealed class EfCoreValueConverter :");
        sb.AppendLine($"            Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConverter<{model.TypeName}, {backingTypeName}>");
        sb.AppendLine("        {");
        sb.AppendLine($"            /// <summary>Initialises a new <see cref=\"EfCoreValueConverter\"/>.</summary>");
        sb.AppendLine($"            public EfCoreValueConverter()");
        sb.AppendLine($"                : base(id => id.Value, value => new {model.TypeName}(value)) {{ }}");
        sb.AppendLine("        }");
        sb.AppendLine();

        // System.Text.Json converter nested class
        sb.AppendLine($"        /// <summary>System.Text.Json converter for <see cref=\"{model.TypeName}\"/>.</summary>");
        sb.AppendLine($"        public sealed class SystemTextJsonConverter :");
        sb.AppendLine($"            System.Text.Json.Serialization.JsonConverter<{model.TypeName}>");
        sb.AppendLine("        {");
        sb.AppendLine($"            /// <inheritdoc/>");
        sb.AppendLine($"            public override {model.TypeName} Read(");
        sb.AppendLine($"                ref System.Text.Json.Utf8JsonReader reader,");
        sb.AppendLine($"                System.Type typeToConvert,");
        sb.AppendLine($"                System.Text.Json.JsonSerializerOptions options)");
        sb.AppendLine($"                => new({jsonReadExpr});");
        sb.AppendLine();
        sb.AppendLine($"            /// <inheritdoc/>");
        sb.AppendLine($"            public override void Write(");
        sb.AppendLine($"                System.Text.Json.Utf8JsonWriter writer,");
        sb.AppendLine($"                {model.TypeName} value,");
        sb.AppendLine($"                System.Text.Json.JsonSerializerOptions options)");
        sb.AppendLine($"                => writer.{jsonWriteMethod}(value.Value);");
        sb.AppendLine("        }");

        sb.AppendLine("    }");

        if (model.Namespace is not null)
            sb.AppendLine("}");

        return sb.ToString();
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private static (string typeName, string jsonRead, string jsonWrite, bool hasNew, bool hasEmpty)
        GetBackingTypeInfo(BackingTypeKind kind) => kind switch
    {
        BackingTypeKind.Guid   => ("System.Guid",   "reader.GetGuid()",    "WriteStringValue", hasNew: true,  hasEmpty: true),
        BackingTypeKind.Int    => ("int",            "reader.GetInt32()",   "WriteNumberValue", hasNew: false, hasEmpty: false),
        BackingTypeKind.Long   => ("long",           "reader.GetInt64()",   "WriteNumberValue", hasNew: false, hasEmpty: false),
        BackingTypeKind.String => ("string",         "reader.GetString()!", "WriteStringValue", hasNew: false, hasEmpty: false),
        _                      => ("System.Guid",   "reader.GetGuid()",    "WriteStringValue", hasNew: true,  hasEmpty: true),
    };
}
